### ISSUE TITLE
Составить список команды

### ISSUE THREAD

**Issue by stden** [levelp/CppTickets#2]
- Александр Медведев
- Алексей Васильев
- Алексей Королев
- Арсений Миронов
- Иван Зелтинь
- Матвей Захаров
- Руслан Машкевич

**Comment by Lisss13** [comment]
Arseniy

**Comment by alexey257** [comment]
Алексей В

**Comment by JamesForster** [comment]
Машкевич Руслан

**Comment by Lisss13** [comment]
Нормуль

**Comment by m1nsk** [comment]
Королев А

**Comment by Lisss13** [comment]
все привет

**Comment by IvanZelts** [comment]
Зелтинь Иван
